### ISSUE TITLE
Inaccurate 'Can only affect your own account' error

### ISSUE THREAD

**Issue by NickBolles** [feathers-plus/authentication-local-management#9]
### Steps to reproduce

- [x] Tell us what broke. The more detailed the better.
- [ ] Include the `feathers-gen-specs.json` file from your app.
- [ ] Include the `src/services/[serviceName]/[serviceName].schema.?s` files if the issue involves the fields in one or more services.

I verified that password change is sending the correct user, auth token and such down to the server. Then on this [line](https://github.com/feathers-plus/authentication-local-management/blob/6f1c12709beb42150dd47fa9b3a9887878941f7d/src/password-change.js#L27)

the authUser Id and the user1 (from the db) id are identical, but using === directly on them still returns false. 

Changing this line to stringify the ids fixes the issue
```
  if (options.ownAcctOnly && authUser && (`${getId(authUser)}` !== `${getId(user1)}`)) {
```

It might also make sense to do this in the [get-id helper](https://github.com/feathers-plus/authentication-local-management/blob/6f1c12709beb42150dd47fa9b3a9887878941f7d/src/helpers/get-id.js)?

**Comment by eddyystop** [comment]
Thanks for the catch!

Did you use Mongoose or MongoDB? The keys would be ObjectIDs in that case.

getId now does a .toString() on the key.

Please remember this repo has not yet been released. Beaking changes are likely and I push changes to master directly so there are no PRs to look at.
